version: '3.4'

services:
  longestincreasingsubsequence:
    image: ${DOCKER_REGISTRY-}longestincreasingsubsequence
    build:
      context: .
      dockerfile: LongestIncreasingSubsequence/Dockerfile
  tests:
    container_name: longestincreasingsubsequence
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./LongestIncreasingSubsequence:/LongestIncreasingSubsequence
      - ./LongestIncreasingSubsequence.Tests:/LongestIncreasingSubsequence.Tests
    working_dir: /LongestIncreasingSubsequence
    command:
      [
        "dotnet",
        "test",
        "LongestIncreasingSubsequence.Tests/LongestIncreasingSubsequence.Tests.csproj"
      ]
    depends_on:
      - longestincreasingsubsequence