version: '3.4'

services:
  longestincreasingsubsequence:
    image: ${DOCKER_REGISTRY-}longestincreasingsubsequence
    build:
      context: .
      dockerfile: LongestIncreasingSubsequence/Dockerfile
